_format_version: "2.1"

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${SUPABASE_ANON_KEY}
  - username: service_role
    keyauth_credentials:
      - key: ${SUPABASE_SERVICE_KEY}

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

services:
  # Auth Service
  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1-route
        paths:
          - /auth/v1/
        strip_path: true
    plugins:
      - name: cors

  # REST Service
  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1-route
        paths:
          - /rest/v1/
        strip_path: true
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
          key_names:
            - apikey
          run_on_preflight: false

  # Realtime Service
  - name: realtime-v1
    url: http://realtime:4000/
    routes:
      - name: realtime-v1-route
        paths:
          - /realtime/v1/
        strip_path: true
    plugins:
      - name: cors

  # Storage Service
  - name: storage-v1
    url: http://storage:5000/
    routes:
      - name: storage-v1-route
        paths:
          - /storage/v1/
        strip_path: true
    plugins:
      - name: cors

  # Meta Service
  - name: meta
    url: http://meta:8080/
    routes:
      - name: meta-route
        paths:
          - /pg/
        strip_path: true
    plugins:
      - name: key-auth
        config:
          hide_credentials: false
          key_names:
            - apikey
          run_on_preflight: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
            - admin
